import Head from 'next/head'
import Nav from '../components/nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Carlan Henry</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Nav />
    </div>
  )
}
